# Generated by Django 5.0.3 on 2024-03-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studyMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('course', models.CharField(max_length=100)),
                ('semister', models.CharField(max_length=50)),
            ],
        ),
    ]
