# Generated by Django 5.0.3 on 2024-03-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_department_studymaterial_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='semister',
            field=models.CharField(choices=[('first', 'First sem'), ('second', 'Second sem'), ('third', 'Third sem'), ('fourth', 'Fourth sem'), ('fifth', 'Fifth sem'), ('sixth', 'sixth sem')], max_length=50),
        ),
    ]
