# Generated by Django 5.0.3 on 2024-03-10 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_studymaterial_description_subject_semister'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notes.department'),
        ),
    ]
