# Generated by Django 5.0.3 on 2024-03-12 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_studymaterial_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semisters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterialTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='semister',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notes.semisters'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semister',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notes.semisters'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notes.studymaterialtypes'),
        ),
    ]
