# Generated by Django 5.0.3 on 2024-03-12 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_semisters_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='semister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.semisters'),
        ),
    ]
